In [1]:
import numpy as np
import pandas as pd
import matplotlib
# import matplotlib.pyplot as plt
# import seaborn as sns
import warnings
import gc
import sys
import pickle
from sklearn.preprocessing import OneHotEncoder

In [2]:
with open('train_1124', 'rb') as f:
    OH_X_train = pickle.load(f)
with open('test_1124', 'rb') as f:
    OH_X_test = pickle.load(f)

In [3]:
OH_X_train.shape

(19770715, 27)

In [4]:
OH_X_test.shape

(41498571, 27)

In [5]:
# modify at 2/12,

In [6]:
OH_X_train = OH_X_train.drop(['has_year','has_floorcnt'],axis=1)
OH_X_test = OH_X_test.drop(['has_year','has_floorcnt'],axis=1)

In [7]:
with pd.option_context('display.max_rows', None):
    print(OH_X_train.dtypes)

building_id            uint16
meter                   uint8
timestamp              object
meter_reading         float32
site_id                 uint8
primary_use            object
square_feet            uint32
floor_count             uint8
age                     uint8
precip_true_1_hr        uint8
weekday                 uint8
hour                    uint8
month                   uint8
air_temperature       float32
cloud_coverage         uint16
dew_temperature       float32
precip_depth_1_hr     float32
sea_level_pressure    float32
wind_direction          uint8
wind_speed            float32
humidity              float32
apparent_temp         float32
min_temperature       float32
max_temperature       float32
mean_temperature      float32
dtype: object

In [8]:
OH_X_train['hour'] = pd.Series(OH_X_train['hour']/3, dtype='uint8')
OH_X_test['hour'] = pd.Series(OH_X_test['hour']/3, dtype='uint8')

In [9]:
onehot_list = ['primary_use','month','weekday','hour','wind_direction']

In [10]:
OH_X_train = pd.get_dummies(OH_X_train,columns=onehot_list)
OH_X_test = pd.get_dummies(OH_X_test,columns=onehot_list)

In [11]:
OH_X_train.shape

(19770715, 71)

In [12]:
OH_X_test.shape

(41498571, 71)

In [13]:
display(OH_X_train)

,building_id,meter,timestamp,meter_reading,site_id,square_feet,floor_count,age,precip_true_1_hr,air_temperature,...,hour_6,hour_7,wind_direction_0,wind_direction_1,wind_direction_2,wind_direction_3,wind_direction_4,wind_direction_5,wind_direction_6,wind_direction_7
103,105,0,2016-01-01 00:00:00,23.303600,1,50623,5,54,0,3.8,...,0,0,0,0,0,0,0,1,0,0
104,106,0,2016-01-01 00:00:00,0.374600,1,5374,4,54,0,3.8,...,0,0,0,0,0,0,0,1,0,0
105,106,3,2016-01-01 00:00:00,0.000000,1,5374,4,54,0,3.8,...,0,0,0,0,0,0,0,1,0,0
106,107,0,2016-01-01 00:00:00,175.184006,1,97532,10,12,0,3.8,...,0,0,0,0,0,0,0,1,0,0
107,108,0,2016-01-01 00:00:00,91.265297,1,81580,5,104,0,3.8,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20216095,1444,0,2016-12-31 23:00:00,8.750000,15,19619,2,103,0,1.7,...,0,1,0,0,0,0,1,0,0,0
20216096,1445,0,2016-12-31 23:00:00,4.825000,15,4298,0,54,0,1.7,...,0,1,0,0,0,0,1,0,0,0
20216097,1446,0,2016-12-31 23:00:00,0.000000,15,11265,1,20,0,1.7,...,0,1,0,0,0,0,1,0,0,0
20216098,1447,0,2016-12-31 23:00:00,159.574997,15,29775,2,16,0,1.7,...,0,1,0,0,0,0,1,0,0,0
20216099,1448,0,2016-12-31 23:00:00,2.850000,15,92271,7,16,0,1.7,...,0,1,0,0,0,0,1,0,0,0

In [14]:
display(OH_X_test)

,row_id,building_id,meter,timestamp,site_id,square_feet,floor_count,age,precip_true_1_hr,air_temperature,...,hour_6,hour_7,wind_direction_0,wind_direction_1,wind_direction_2,wind_direction_3,wind_direction_4,wind_direction_5,wind_direction_6,wind_direction_7
0,0,0,0,2017-01-01 00:00:00,0,7432,0,9,0,17.799999,...,0,0,0,0,1,0,0,0,0,0
1,1,1,0,2017-01-01 00:00:00,0,2720,0,13,0,17.799999,...,0,0,0,0,1,0,0,0,0,0
2,2,2,0,2017-01-01 00:00:00,0,5376,0,26,0,17.799999,...,0,0,0,0,1,0,0,0,0,0
3,3,3,0,2017-01-01 00:00:00,0,23685,1,15,0,17.799999,...,0,0,0,0,1,0,0,0,0,0
4,4,4,0,2017-01-01 00:00:00,0,116607,6,42,0,17.799999,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41498566,41498566,1369,2,2018-12-31 23:00:00,15,53194,5,64,0,3.300000,...,0,1,0,0,0,1,0,0,0,0
41498567,41498567,1402,0,2018-12-31 23:00:00,15,133594,11,56,0,3.300000,...,0,1,0,0,0,1,0,0,0,0
41498568,41498568,1417,2,2018-12-31 23:00:00,15,40451,3,42,0,3.300000,...,0,1,0,0,0,1,0,0,0,0
41498569,41498569,1431,2,2018-12-31 23:00:00,15,111360,9,17,0,3.300000,...,0,1,0,0,0,1,0,0,0,0
41498570,41498570,1448,0,2018-12-31 23:00:00,15,92271,7,16,0,3.300000,...,0,1,0,0,0,1,0,0,0,0

In [15]:
with pd.option_context('display.max_rows', None):
    print(OH_X_test.dtypes)

row_id                                        uint32
building_id                                   uint16
meter                                          uint8
timestamp                                     object
site_id                                        uint8
square_feet                                   uint32
floor_count                                    uint8
age                                            uint8
precip_true_1_hr                               uint8
air_temperature                              float32
cloud_coverage                                uint16
dew_temperature                              float32
precip_depth_1_hr                            float32
sea_level_pressure                           float32
wind_speed                                   float32
humidity                                     float32
apparent_temp                                float32
min_temperature                              float32
max_temperature                              float32
mean_temperature                             float32
primary_use_Education                          uint8
primary_use_Entertainment/public assembly      uint8
primary_use_Food sales and service             uint8
primary_use_Healthcare                         uint8
primary_use_Lodging/residential                uint8
primary_use_Manufacturing/industrial           uint8
primary_use_Office                             uint8
primary_use_Other                              uint8
primary_use_Parking                            uint8
primary_use_Public services                    uint8
primary_use_Religious worship                  uint8
primary_use_Retail                             uint8
primary_use_Services                           uint8
primary_use_Technology/science                 uint8
primary_use_Utility                            uint8
primary_use_Warehouse/storage                  uint8
month_0                                        uint8
month_1                                        uint8
month_2                                        uint8
month_3                                        uint8
month_4                                        uint8
month_5                                        uint8
month_6                                        uint8
month_7                                        uint8
month_8                                        uint8
month_9                                        uint8
month_10                                       uint8
month_11                                       uint8
weekday_0                                      uint8
weekday_1                                      uint8
weekday_2                                      uint8
weekday_3                                      uint8
weekday_4                                      uint8
weekday_5                                      uint8
weekday_6                                      uint8
hour_0                                         uint8
hour_1                                         uint8
hour_2                                         uint8
hour_3                                         uint8
hour_4                                         uint8
hour_5                                         uint8
hour_6                                         uint8
hour_7                                         uint8
wind_direction_0                               uint8
wind_direction_1                               uint8
wind_direction_2                               uint8
wind_direction_3                               uint8
wind_direction_4                               uint8
wind_direction_5                               uint8
wind_direction_6                               uint8
wind_direction_7                               uint8
dtype: object

In [16]:
with open('train_XGB_1124', 'wb') as f:
    pickle.dump(OH_X_train, f)
with open('test_XGB_1124', 'wb') as f:
    pickle.dump(OH_X_test, f)